### ISSUE TITLE
split is not a function

### ISSUE THREAD

**Issue by stephenplusplus** [stephenplusplus/split-array-stream#2]
@JustinBeckwith I'm new here-- can we not just export the function, so that this is allowed?

```js
const split = require('split-array-stream')
split(...)
```

With 2.0.0, we have to do:

```js
const split = require('split-array-stream')
split.split(...)
```

**Comment by JustinBeckwith** [comment]
Agh, I forgot about that.  This is an issue with es modules as far as I can tell.  In commonjs module land, you'd say:

```js
const {split} = require('split-array-stream');
```

In es module land:

```js
import {split} from 'split-array-stream';
```

I haven't found a way to get a default function export that's both es module and commonjs compatible using the old-school requires :( It's possible @mylesborins knows a trick here I don't :)

**Comment by stephenplusplus** [comment]
I think that @ didn't work!

**Comment by JustinBeckwith** [comment]
Oops :)
